#include "Display_HAL.h"

#define BLK {0, 0, 0, 0xFF}
#define WHT {0xFF, 0xFF, 0xFF, 0xFF}
#define CLR {0,0,0,0}

PIXEL_32BIT cursorImage[16][16] = {
    { BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
    { BLK, BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
    { BLK, WHT, BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
    { BLK, WHT, WHT, BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
    { BLK, WHT, WHT, WHT, BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
    { BLK, WHT, WHT, WHT, WHT, BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
    { BLK, WHT, WHT, WHT, WHT, WHT, BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
    { BLK, WHT, WHT, WHT, WHT, WHT, WHT, BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
    { BLK, WHT, WHT, BLK, BLK, BLK, BLK, BLK, BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
    { BLK, WHT, BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
    { BLK, WHT, BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
    { BLK, BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
    { BLK, BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
    { BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
    { BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
    { BLK, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR, CLR },
};

PIXEL_32BIT areaUnderCursor[16][16] = { BLK };